# 异常

异常是指在程序运行过程中所发生的**不正常的事件**，它会**中断正在运行的程序**；

当异常出现后我们应该做什么？

可以在程序中**预先设置好异常的处理方法**，这样当异常发生时，我们可以对异常进行处理，让程序可以正常运行。

# try-catch-finally

Java 的异常处理是通过 5 个关键字来实现的：`try`、`catch`、`finally`、`throw`、`throws`。

`try`：执行可能产生异常的代码

`catch`：捕获异常

`finally`：无论是否发生异常，代码总能执行

`throws`：声明方法可能要抛出的各种异常

`throw`：手动抛出异常

---

```java
try {
  // 代码块 1
  // 产生异常的代码段 2
} catch(异常类型 ex) {
  // 对异常进行处理的代码段 3
} finally {
  // 代码段 4
}
```

1. `try` 中无异常，不执行 `catch` ，直接执行 `finally`
2. `try` 中有异常，执行 `catch` 块，对异常进行处理，然后执行 `finally`
3. `finally` 一般是释放资源的代码块，`finally` 无论异常是否产生都会执行

---

- 除 0 异常
- 我们都知道，不能将一个数字除以 0，下面试一下，让一个数字除以 0 ，看一下 Java 编译器会给我们什么异常提示。

```java
package scu.test_2024_10_2.package_23_53;

import java.util.Scanner;

public class Main {
    public static void main(String[] args) {
        Scanner input = new Scanner(System.in);
        System.out.println("Enter n1: ");
        int n1 = input.nextInt();
        System.out.println("Enter n2: ");
        int n2 = input.nextInt();
        int res = 0;
        try {
            res = n1 / n2;
            System.out.println(res);
        } catch (Exception ex) {
            System.err.println("除数不能为 0");
        } finally {
            System.out.println("程序结束");
        }
    }
}
```

# 异常对象的常用方法

| 方法名                   | 说明                                                         |
| ------------------------ | ------------------------------------------------------------ |
| `void printStackTrace()` | 输出异常的堆栈信息                                           |
| `String getMessage()`    | 返回异常信息描述字符串，是 `printStackTrace()` 输出信息的一部分 |

异常对象的一个方法 `printStackTrace()` ：打印异常的引发详细的信息，包括异常的类型、异常的文字信息（英文信息）、引发错误代码的行数。

---

```java
package scu.test_2024_10_2.package_23_53;

import java.util.Scanner;

public class Main {
    public static void main(String[] args) {
        Scanner input = new Scanner(System.in);
        System.out.println("Enter n1: ");
        int n1 = input.nextInt();
        System.out.println("Enter n2: ");
        int n2 = input.nextInt();
        try {
           int res = n1 / n2;
            System.out.println(res);
        } catch (Exception ex) {
            System.err.println("除数不能为 0");
            ex.printStackTrace();
            System.out.println(ex.getMessage());
        } finally {
            System.out.println("程序结束");
        }
    }
}
```

# 有 `return` 的情况

```java
try {
  // 代码块 1
  // 产生异常的代码段 2
} catch(异常类型 ex) {
  // 对异常进行处理的代码段 3
  return;
} finally {
  // 代码块 4
}
```

<img src="https://leafalice-image.oss-cn-hangzhou.aliyuncs.com/img/image-20241003121604730.png" alt="image-20241003121604730" style="zoom:67%;" />

`finally` 仍然会执行。

# 多路异常捕获

- 捕获 `catch` 语句的顺序：先子类后父类
- 发生异常时按顺序逐个匹配
- 只执行第一个与异常类型匹配的 `catch` 语句

# 多路异常捕获案例

- `InputMismatchException` 捕获类型异常
- `ArithmeticException` 捕获算术异常
- `Exception` 捕获其他异常

```java
package scu.test_2024_10_3.package_12_34;

import java.util.InputMismatchException;
import java.util.Scanner;

public class Main {
    public static void main(String[] args) {
        Scanner input = new Scanner(System.in);
        try {
            System.out.println("Enter n1: ");
            int n1 = input.nextInt();
            System.out.println("Enter n2: ");
            int n2 = input.nextInt();
            int res = n1 / n2;
            System.out.println(res);
        } catch (InputMismatchException ex) {
            System.out.println("被除数和除数都必须是整数");
        } catch (ArithmeticException ex) {
            System.out.println("除数不能为 0");
        } catch (Exception ex) {
            System.out.println("未知异常");
        } finally {
            System.out.println("程序结束");
        }
    }
}
```

1. 有多个 `catch` 块组成，而且从子类写到父类，最后用 `Exception` 收尾；
2. 多路异常捕获在开发中用的比较多，必须掌握；

# `throws` 进行异常声明

声明异常：

- 在一个方法体中产生了异常，如何通知调用者？
  1. 调用方使用 `try-catch` 捕获异常
  2. 不做处理，继续声明异常

```java
package scu.test_2024_10_3.package_13_09;

public class Main {
    public static void test() throws Exception {
        System.out.println(5 / 0);
    }

    public static void main(String[] args) {
        try {
            test();
        } catch (Exception e) {
            System.out.println("除数不能为零");
        }
    }
}
```

> 使用：
>
> ```java
> public class Main{
>   public static void main(String[] args) throws Exception {
>     // 这种操作将异常抛给 JVM，异常吞掉
>   }
> }
> ```

# `throw` 抛出异常

